# Generated by Django 5.0.2 on 2024-03-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0002_resulthistory_delete_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulthistory',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
    ]
