# Generated by Django 5.0.2 on 2024-03-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0003_resulthistory_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='userFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('body', models.CharField(default='', max_length=50)),
                ('text', models.CharField(max_length=50)),
                ('date', models.DateField(default='1')),
            ],
        ),
    ]
