# Generated by Django 5.0.2 on 2024-03-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0004_userfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeedback',
            old_name='body',
            new_name='textbody',
        ),
    ]
