# Generated by Django 5.0.2 on 2024-03-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0005_rename_body_userfeedback_textbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulthistory',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
